app/views/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash

from ..forms import AuthForm
from ..functions import generate_id, get_base64_encode
from ..app_functions import get_login, user_login_required
from ..db import User, db

auth = Blueprint("Auth", __name__, url_prefix="/auth")

@auth.route("/", methods=("GET", "POST"))
def auth_index():
    if get_login() is True:
        return redirect(url_for("Home.home_index"))

    form = AuthForm(request.form)

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        data = User.query.filter(User.email == email).first()

        if data:
            if check_password_hash(data.password, password):
                session.permanent = True
                session["session-sign-id"] = get_base64_encode(data.session_id)
                return redirect(url_for("Home.home_index"))
            else:
                flash("Incorrect password for entered email account!", "red")
        else:
            hashed_password = generate_password_hash(password, method="pbkdf2:sha256")
            name = email.split("@")[0][:18]
            user = User(
                name=name,
                email=email,
                password=hashed_password,
                session_id=generate_id(name, email, hashed_password)
            )

            db.session.add(user)
            db.session.commit()

            flash("New account has been created, enter credentials to signin.", "green")

        return redirect(url_for(".auth_index"))

    return render_template(
        "auth/index.html",
        title="Login",
        form=form
    )

@auth.route("/logout", methods=["GET", "POST"])
@user_login_required
def logout():
    if "session-sign-id" in session:
        session.pop("session-sign-id")
    session.permanent = False    
    return redirect(url_for(".auth_index"))

app/views/settings.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash

from ..forms import SettingsForm1, SettingsForm2, SettingsForm3
from ..db import db
from ..app_functions import get_current_user, user_login_required


settings = Blueprint("Settings", __name__, url_prefix="/settings")


@settings.route("/", methods=("GET","POST"))
@user_login_required
def settings_index():
    form1 = SettingsForm1(request.form)
    form2 = SettingsForm2(request.form)
    form3 = SettingsForm3(request.form)

    if form1.validate_on_submit():
        name = form1.name.data.strip()

        user = get_current_user()
        user.name = name
        db.session.commit()
        
        flash("Name was changed successfully", "green")
        return redirect(url_for(".settings_index"))

    elif form3.validate_on_submit():
        password = form3.password.data
        new_password = form3.new_password.data
        
        update_password = form3.update_password.data
        delete_account = form3.delete_account.data

        user = get_current_user()

        if check_password_hash(user.password, password):
            if update_password:
                if password == new_password:
                    flash("Could not update the password as same as old password!","red")
                else:
                    user.password = generate_password_hash(new_password)
                    db.session.commit()
                    flash("Password updated successfully","green")

            elif delete_account:
                if password != new_password:
                    flash("current and confirm password does not matched!")
                else:
                    db.session.delete(user)
                    db.session.commit()
                    flash("Account deleted successfully.")
            
            else:
                flash("cannot process your request, tryagain", "red")
            return redirect(url_for("Auth.auth_index"))
        else:
            flash("Incorrect password to perform operation!","red")
            return redirect(url_for(".settings_index"))

    user = get_current_user()

    form1.name.data = user.name
    form2.email.data = user.email

    return render_template(
        "settings/index.html",
        title="Settings",
        form1=form1,
        form2=form2,
        form3=form3,
        footer=True
    )

app/templates/settings/index.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/settings.css') }}">
{% endblock %}

{% block body %}
<div class="shadow-card">
    <div class="form" style="width: 100%; box-shadow: 0px 0px 0px 0px;">
        <a href="{{ url_for('Home.home_index') }}">&lt;&lt; Back to Home</a>
        <h1 style="text-align:center;">Settings</h1>

        <form action="{{ url_for('Settings.settings_index') }}" method="post">
            {{ form1.csrf_token() }}
            <div class="br"></div>
            
            <div class="label">
                <h2>Name</h2>
                {{ form1.name.label }}
                {{ form1.name() }}
                {% if form1.name.errors %}
                    <div class="errors">
                        {% for error in form1.name.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            {{ form1.update_name() }}
        </form>

        <form action="#" method="post">

            <div class="br"></div>
            <div class="label">
                <h2>Email</h2>
                {{ form2.email.label }}
                {{ form2.email() }}
            </div>
            <div class="br"></div>

        </form>

        <form action="{{ url_for('Settings.settings_index') }}" method="post">
            {{ form3.csrf_token() }}
            
            <div class="label" style="margin-bottom: 0px;">
                <h2>Update password</h2>
            </div>

            <div class="label">
                {{ form3.password.label }}
                {{ form3.password() }}
                {% if form3.password.errors %}
                    <div class="errors">
                        {% for error in form3.password.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="label">
                {{ form3.new_password.label }}
                {{ form3.new_password() }}
                {% if form3.new_password.errors %}
                    <div class="errors">
                        {% for error in form3.new_password.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="btns">
                {{ form3.update_password() }}
                {{ form3.delete_account() }}
            </div>

            <div class="br"></div>

        </form>

        <form action="{{ url_for('Auth.logout') }}" method="POST" style="display: flex; flex-direction: row; align-items: center; justify-content: space-between; flex-wrap: wrap;">
            <div class="label">
                <h2>Logout from this device</h2>
            </div>

            <input type="submit" class="w-btn" value="Logout" />
        </form>
    </div>
</div>
{% endblock %}