app/views/home.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, Response, stream_with_context

from ..app_functions import get_current_user, get_current_user_balance, user_login_required
from ..functions import generate_string
from ..forms import NewStatementForm, StatementEditForm
from ..db import db, Statements, User
from sqlalchemy import func


home = Blueprint("Home", __name__)


@home.route("/")
@user_login_required
def home_index():
    user = get_current_user()

    user_details = {}
    user_details["name"] = user.name
    user_details["account_balance"] = round(get_current_user_balance(),2)
    
    statements = Statements.query.filter(Statements.user_id == user.id).order_by(Statements.operation_time.desc()).limit(5).all()

    user_details["statements"] = list(
        {"desc":x.description, "amount":x.amount, "at":x.operation_time, "id": x.statement_id} for x in statements
    )

    return render_template(
        "home/index.html",
        user= user_details
    )

@home.route("/new", methods=("GET","POST"))
@user_login_required
def new_statement():
    form = NewStatementForm(request.form)
    if form.validate_on_submit():
        amount = form.amount.data
        description = form.description.data
        at = form.datetime_data.data
        income = form.income.data
        expense = form.expense.data

        if not income and not expense:
            flash("Cannot add statement that is neither income nor expense!","red")
            return redirect(url_for(".new_statement"))
        
        amount = abs(amount)
        if expense is True:
            amount = -amount

        current_user = get_current_user()
        user_id = current_user.id
        
        statement = Statements(
            description = description,
            amount = amount,
            operation_time = at,
            user_id = user_id,
            statement_id = generate_string()
        )

        db.session.add(statement)
        db.session.commit()

        flash("Statement was added to your account successfully.", "green")
        return redirect(url_for("Home.home_index"))

    return render_template(
        "home/new_statement.html",
        title="New statement",
        form=form
    )

@home.route("/statements")
@user_login_required
def statements():
    try:
        page = int(request.args.get("page","0"))
    except:
        page = 0
    finally:
        if page < 0:
            page = 0

    page_size = 6

    user = get_current_user()

    if request.args.get("t") == "expense":
        statements = Statements.query.filter(Statements.user_id == user.id, Statements.amount < 0).order_by(Statements.operation_time.desc()).limit(page_size).offset(page_size*page).all()
    elif request.args.get("t") == "income":
        statements = Statements.query.filter(Statements.user_id == user.id, Statements.amount >= 0).order_by(Statements.operation_time.desc()).limit(page_size).offset(page_size*page).all()
    else:
        statements = Statements.query.filter(Statements.user_id == user.id).order_by(Statements.operation_time.desc()).limit(page_size).offset(page_size*page).all()

    statements = list(
        {"desc":x.description, "amount":x.amount, "at": str(x.operation_time), "id": x.statement_id} for x in statements
    )

    current_balance = get_current_user_balance()
    total_expense = Statements.query.with_entities(func.sum(Statements.amount)).filter(Statements.user_id == user.id, Statements.amount < 0).first()[0]
    if total_expense is None:
        total_expense = 0.0
    total_expense = abs(total_expense)
    total_income = Statements.query.with_entities(func.sum(Statements.amount)).filter(Statements.user_id == user.id, Statements.amount >= 0).first()[0]
    if total_income is None:
        total_income = 0.0

    if request.args.get("__a") == "1":
        return statements

    date = []
    expense_amount = []
    income_amount = []
    amount = []

    for x in Statements.query.filter(Statements.user_id == user.id).order_by(Statements.operation_time).all():
        date.append(x.operation_time)
        money = x.amount

        amount.append(abs(money))

        if money < 0:
            expense_amount.append(abs(money))
            income_amount.append(None)
        else:
            income_amount.append(money)
            expense_amount.append(None)


    return render_template(
        "home/statements.html",
        title="All statements",
        statements=statements,
        total_income=total_income,
        total_expense=total_expense,
        current_balance=current_balance,
        page_size=page_size,
        round=round
    )

@home.route("/statement/<statement_id>", methods=("GET","POST"))
@user_login_required
def specific_statement(statement_id):
    statement = Statements.query.filter(Statements.statement_id == statement_id).first_or_404()

    form = StatementEditForm(request.form)

    if form.validate_on_submit():
        amount = form.amount.data
        description = form.description.data
        date_time = form.datetime_data.data
        
        income = form.income.data
        expense = form.expense.data
        delete = form.delete_statement.data

        amount = abs(amount)

        if income is True:
            statement.amount = amount
            statement.description = description
            statement.operation_time = date_time

            db.session.commit()

            flash("Updated statement as income successfully", "green")
        
        elif expense is True:
            statement.amount = -amount
            statement.description = description
            statement.operation_time = date_time

            db.session.commit()

            flash("Updated statement as expense successfully", "green")

        elif delete is True:
            db.session.delete(statement)
            db.session.commit()

            flash("The statement was deleted successfully", "green")

            return redirect(url_for(".home_index"))

        else:
            flash("Unsupported action to perform!", "red")
        
        return redirect(url_for(".specific_statement", statement_id=statement_id))

    form.amount.data = abs(statement.amount)
    form.description.data = statement.description
    form.datetime_data.data = statement.operation_time


    return render_template(
        "home/statement.html",
        title="Statement",
        form=form,
        statement_id=statement_id
    )

@home.route("/download-statements")
@user_login_required
def download_statements():
    user = get_current_user()
    statements = Statements.query.filter(Statements.user_id == user.id)

    content_disposition = "attachment; filename={}'s-statements.csv".format(user.name)
    
    def data():
        first_iter = True
        for statement in statements.yield_per(5):
            if first_iter is True:
                first_iter = False
                yield "amount, description, datetime, type\n"

            if statement.amount < 0:
                statement_type = "expense"
            else:
                statement_type = "income"
            yield f"{abs(statement.amount)},{statement.description},{statement.operation_time.isoformat()},{statement_type}\n"

    return Response(stream_with_context(data()), 200, mimetype="text/csv",headers={
        "Content-Disposition" : content_disposition
    })

app/views/settings.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash

from ..forms import SettingsForm1, SettingsForm2, SettingsForm3
from ..db import db
from ..app_functions import get_current_user, user_login_required


settings = Blueprint("Settings", __name__, url_prefix="/settings")


@settings.route("/", methods=("GET","POST"))
@user_login_required
def settings_index():
    form1 = SettingsForm1(request.form)
    form2 = SettingsForm2(request.form)
    form3 = SettingsForm3(request.form)

    if form1.validate_on_submit():
        name = form1.name.data.strip()

        user = get_current_user()
        user.name = name
        db.session.commit()
        
        flash("Name was changed successfully", "green")
        return redirect(url_for(".settings_index"))

    elif form3.validate_on_submit():
        password = form3.password.data
        new_password = form3.new_password.data
        
        update_password = form3.update_password.data
        delete_account = form3.delete_account.data

        user = get_current_user()

        if check_password_hash(user.password, password):
            if update_password:
                if password == new_password:
                    flash("Could not update the password as same as old password!","red")
                else:
                    user.password = generate_password_hash(new_password)
                    db.session.commit()
                    flash("Password updated successfully","green")

            elif delete_account:
                if password != new_password:
                    flash("current and confirm password does not matched!")
                else:
                    db.session.delete(user)
                    db.session.commit()
                    flash("Account deleted successfully.")
            
            else:
                flash("cannot process your request, tryagain", "red")
            return redirect(url_for("Auth.auth_index"))
        else:
            flash("Incorrect password to perform operation!","red")
            return redirect(url_for(".settings_index"))

    user = get_current_user()

    form1.name.data = user.name
    form2.email.data = user.email

    return render_template(
        "settings/index.html",
        title="Settings",
        form1=form1,
        form2=form2,
        form3=form3,
        footer=True
    )

app/templates/home/index.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/statements.css') }}">
{% endblock %}

{% block body %}
<div class="shadow-card" id="expense-card">
    <div id="name">Hello, {{ user.name }}</div>
    <div id="top">
        <div class="part" style="display: flex;flex-direction: column;align-items:center;justify-content:center;">
            <div id="balance">
                <span id="currency">&#8377;</span>
                <span id="num">{{ user.account_balance }}</span>
            </div>
        </div>
        <div class="part">
            <div id="operations">
                <a class="btn-a" href="{{ url_for('Home.new_statement') }}">Add statement</a>
                <a class="btn-a" href="{{ url_for('Home.statements') }}">View statements</a>
                <a class="btn-a" href="{{ url_for('Settings.settings_index') }}">Settings</a>
            </div>
        </div>
    </div>
    <div id="bottom" class="part">
        <h1>Last statements</h1>
        <div id="statements">
            {% if user.statements %}
                {% for statement in user.statements %}
                    <a href="{{ url_for('Home.specific_statement', statement_id=statement.id) }}" class="statement">
                        <div>
                            <div class="desc">{{statement.desc}}</div>
                            <div class="at">{{statement.at}}</div>
                        </div>
                        <div class="amount">&#8377;{{statement.amount}}</div>
                    </a>
                {% endfor %}
            {% else %}
                <p>You've not added any statements yet.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/new_statement.html
{% extends "base.html" %}

{% block body %}
<div class="form">
    <a href="{{ url_for('Home.home_index') }}">&lt;&lt; Back to Home</a>
    <h1>Add Statement</h1>
    <form action="{{ url_for('Home.new_statement') }}" method="post">
        {{ form.csrf_token() }}
        <div class="label">
            {{ form.amount.label }}
            {{ form.amount() }}
            {% if form.amount.errors %}
                <div class="errors">
                    {% for error in form.amount.errors %}
                        <p>{{error}}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="label">
            {{ form.description.label }}
            {{ form.description() }}
            {% if form.description.errors %}
                <div class="errors">
                    {% for error in form.description.errors %}
                        <p>{{error}}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="label">
            {{ form.datetime_data.label }}
            {{ form.datetime_data() }}
            {% if form.datetime_data.errors %}
                <div class="errors">
                    {% for error in form.datetime_data.errors %}
                        <p>{{error}}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        {{ form.expense }}
        {{ form.income }}
    </form>
</div>
{% endblock %}

app/templates/home/statement.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/settings.css') }}">
{% endblock %}

{% block body %}

<div class="shadow-card">
    <div class="form" style="width: 100%; box-shadow: 0px 0px 0px 0px;">
        <a href="{{ url_for('Home.home_index') }}">&lt;&lt; Back to Home</a>
        <h1>Statement details</h1>
        <form action="{{ url_for('Home.specific_statement', statement_id=statement_id) }}" method="post">
            {{ form.csrf_token() }}
            <div class="label">
                {{ form.amount.label }}
                {{ form.amount() }}
                {% if form.amount.errors %}
                    <div class="errors">
                        {% for error in form.amount.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="label">
                {{ form.description.label }}
                {{ form.description() }}
                {% if form.description.errors %}
                    <div class="errors">
                        {% for error in form.description.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="label">
                {{ form.datetime_data.label }}
                {{ form.datetime_data() }}
                {% if form.datetime_data.errors %}
                    <div class="errors">
                        {% for error in form.datetime_data.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="btns">
                {{ form.expense }}
                {{ form.income }}
                {{ form.delete_statement }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/home/statements.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/statements.css') }}">

<script>
    let current_page = 1;
    const page_size = {{ page_size }};
    const path = `{{url_for('Home.specific_statement', statement_id="")}}`

    const load_more = (element) => {
        element.disabled = true;
        element.style.cursor = "progress"

        fetch(`{{ url_for("Home.statements",t=request.args.get('t'),__a=1 )|safe }}&page=${current_page}`)
        .then(resp => resp.json())
        .then(data => {
            current_page++;

            if(!data || data.length === 0){
                element.remove()
                return;
            }

            data.forEach(statement => {

                const state = document.createElement("a")
                state.href = path+statement.id
                state.classList.add("statement")

                const div_1 = document.createElement("div")

                const desc = document.createElement("div")
                desc.innerText = statement.desc;
                desc.classList.add("desc")
                const at = document.createElement("div")
                at.classList.add("at")
                at.innerText = statement.at

                div_1.appendChild(desc)
                div_1.appendChild(at)

                const amount = document.createElement("div")
                amount.classList.add("amount")
                amount.innerHTML = '&#8377';
                amount.innerText += statement.amount;

                state.append(div_1,amount)

                document.getElementById("statements").append(state)
            })

            if(data.length >= page_size){
                const node = element.cloneNode(true)
                node.disabled = false;
                node.style.cursor = "pointer"
                element.parentElement.appendChild(node);
            } else {
                const end_note = document.createElement("div")
                end_note.innerText = "You've caught your all statements"
            }
            element.remove()

        })
        .catch(error=>{
            alert("Something went wrong, tryagain later.")
            console.log(error);
            element.disabled = false;
            element.style.cursor = "cursor"
        })
    }
</script>
{% endblock %}

{% block body %}
<div class="shadow-card">
    <div class="shadow-card">
        <a href="{{ url_for('Home.home_index') }}">&lt;&lt; Back to Home</a>
    </div>
    <h1 style="text-align: center;">Statements</h1>
    <div class="details-e">
        <div class="part-d">
            <div class="head">Total Income</div>
            <div class="money"><span>&#8377;</span><span>{{round(total_income,3)}}</span></div>
        </div>
        <div class="part-d">
            <div class="head">Total Expense</div>
            <div class="money"><span>&#8377;</span><span>{{round(total_expense,3)}}</span></div>
        </div>
        <div class="part-d">
            <div class="head">Current balance</div>
            <div class="money"><span>&#8377;</span><span>{{round(current_balance,3)}}</span></div>
        </div>
        <a href="{{ url_for('Home.download_statements') }}" class="part-d" style="display: flex;align-items: center;justify-content: center;">Download statements</a>
    </div>

    <div>
        <select id="type">
            <option {{ "selected" if not request.args.get("t") or request.args.get("t") == "" }} >View all statements</option>
            <option {{ "selected" if request.args.get("t") == "expense" }} value="expense">View Expense statements</option>
            <option {{ "selected" if request.args.get("t") == "income" }} value="income">View Income statements</option>
        </select>
    </div>

    <div id="statements">
        {% if statements %}
            {% for statement in statements %}
                <a href="{{ url_for('Home.specific_statement', statement_id=statement.id) }}" class="statement">
                    <div>
                        {{statement.statement_id}}
                        <div class="desc">{{statement.desc}}</div>
                        <div class="at">{{statement.at}}</div>
                    </div>
                    <div class="amount">&#8377;{{statement.amount}}</div>
                </a>
            {% endfor %}
            <button type="button" onclick="load_more(this)" class="btn" style="cursor: pointer; width: max-content; margin: 10px auto;">Load more</button>
        {% else %}
            <p>You've not added any statements yet.</p>
        {% endif %}
    </div>
</div>

<script>
    document.getElementById("type").onchange = (e) => {
        const url = new URL(window.location.href);
        url.searchParams.set("t",e.target.value)
        window.location.href = url.toString()
    }
</script>
{% endblock %}